FORMAT: 1A
HOST: https://ancestree.site/api/

# 快点

API for 快点

## Authorization [/auth]

### Get an openid [GET /openid{?code}]

+ Parameters

    - code : `code` (string) - Code of User

+ Response 200 (application/json)

        {
            "status":"OK",
            "message":"获得成功",
            "data": "{\"session_key\":\"TlJlfw+8gIpHbCgNy1Jrdw==\",\"openid\":\"oKIqG5AD7pu1-nHypI2z-mP7SswU\"}"
        }

        // 失败返回（code已经被使用过）

        {
            "status": "OK",
            "message": "获取成功",
            "data": "{\"errcode\":40163,\"errmsg\":\"code been used, hints: [ req_id: dcQq0a0498th40 ]\"}"
        }

### Get a JWT [GET /auth{?username,password,type}]

+ Parameters

    - username : type=1: openid, type=2: account (string) - Username
    - password : password (string) - Password
    - type : 0 (int) - User type (0-Admin, 1-User, 2-Marchant)

+ Response 200 (application/json)

        {
            "status":"OK",
            "message":"验证成功",
            "data": {
                "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ"
            }
        }

## Users [/users]

### Create/Update a New User [POST]

+ Request (application/json)

        {
            "open_id": "abc",
            "nick_name": "快点",
            "avatar": "https://api.kuaidian.com/a.png",
            "tel": "13719176589"
        }

+ Response 201 (application/json)

    + Headers

            Location: /users/open_id

    + Body

            {
                "status": "OK",
                "message": "成功创建/更新用户",
                "data": {
                    "open_id": "123",
                    "nick_name": "Adc123",
                    "avatar": "avatar",
                    "tel": "tel"
                },
                "createdAt": "2018-06-25 21:59:30.225861046 +0800 CST m=+8.722275647"
            }

### Get Users [GET]

+ Response 200 (application/json)

        {
            "status": "OK",
            "message": "成功获取用户列表",
            "data": [
                {
                    "open_id": "12",
                    "nick_name": "astaxie",
                    "avatar": "研发部门",
                    "tel": "2012-12-09"
                },
                {
                    "open_id": "a1",
                    "nick_name": "yohn",
                    "avatar": "assht",
                    "tel": "ash"
                }
            ],
            "createdAt": "2018-06-25 03:58:16.745911882 +0800 CST m=+9.041847753"
        }

### Get an User by OpenID [GET /users/open_id]

+ Response 200 (application/json)

        {
            "status": "OK",
            "message": "成功获取用户",
            "data": {
                "open_id": "",
                "nick_name": "astaxie",
                "avatar": "研发部门",
                "tel": "2012-12-09"
            },
            "createdAt": "2018-06-25 04:08:11.788470733 +0800 CST m=+169.779756203"
        }

## Merchants [/merchants]

### Get all Merchants [GET]

+ Response 200 (application/json)

        {
            "status": "OK",
            "message": "成功获取",
            "data": [
                {
                    "id": 1,
                    "name": "abc",
                    "logo": "https://api.kuaidian.com/a.png",
                    "tel": "12341341234",
                    "address": "广州大学城",
                    "introduction": "xxx",
                    "onsales": "xxx优惠十元",
                    "openTime": "9:30-20:00",
                    "open": true,
                    "score": 4.3,
                }, {
                    "id": 2,
                    "name": "abc",
                    "logo": "https://api.kuaidian.com/a.png",
                    "tel": "12341341234",
                    "address": "广州大学城",
                    "introduction": "xxx",
                    "onsales": "xxx优惠十元",
                    "openTime": "9:30-20:00",
                    "open": true,
                    "score": 4.3,
                }
            ]
        }

### Create a New Merchant [POST]

+ Request (application/json)

        {
            "name": "abc",
            "logo": "https://api.kuaidian.com/a.png",
            "tel": "12341341234",
            "address": "广州大学城",
        }

+ Response 201 (application/json)

    + Headers

            Location: /merchants/merchant_id

    + Body

            {
                "status": "OK",
                "message": "成功创建",
                "data": {
                    "id": 2,
                    "name": "abc",
                    "logo": "https://api.kuaidian.com/a.png",
                    "tel": "12341341234",
                    "address": "广州大学城",
                }
            }

### Get a Merchant By Tel [GET /merchants/tel]

+ Response 200 (application/json)

        {
            "status": "OK",
            "message": "成功获取",
            "data": {
                "id": 2,
                "name": "abc",
                "logo": "https://api.kuaidian.com/a.png",
                "tel": "12341341234",
                "address": "广州大学城",
                "introduction": "xxx",
                "onsales": "xxx优惠十元",
                "openTime": "9:30-20:00",
                "open": true,
                "score": 4.3,
            }
        }

### Update a Merchant [POST /merchants]

+ Request (application/json)

        {
            "id": 2,
            "name": "abc",
            "logo": "https://api.kuaidian.com/a.png",
            "tel": "12341341234",
            "address": "广州大学城",
            "introduction": "xxx",
            "onsales": "xxx优惠十元",
            "openTime": "9:30-20:00",
            "open": true,
            "score": 4.3,
        }

+ Response 200 (application/json)

        {
            "status": "OK",
            "message": "成功更新",
            "data": {
                "id": 2,
                "name": "abc",
                "logo": "https://api.kuaidian.com/a.png",
                "tel": "12341341234",
                "address": "广州大学城",
                "introduction": "xxx",
                "onsales": "xxx优惠十元",
                "openTime": "9:30-20:00",
                "open": true,
                "score": 4.3,
            }
        }

## Foods [/foods]

### Get all Foods by MerchantID [GET /foods?merchant_id=?]

+ Response 200 (application/json)

        {
            "status": "OK",
            "message": "成功获取",
            "data": [
                {
                    "food_id": 1,
                    "merchant_id": 1,
                    "name": "巨无霸",
                    "image": "https://api.kuaidian.com/a.png",
                    "type": "汉堡,新品",
                    "price": 100.5,
                    "introduction": "由牛肉组成"
                }, {
                    "food_id": 2,
                    "merchant_id": 1,
                    "name": "巨无霸1",
                    "image": "https://api.kuaidian.com/a.png",
                    "type": "汉堡",
                    "price": 20,
                    "introduction": "由青菜组成"
                }
            ]
        }

### Create a New Food [POST]

属性必须含有merchant_id

+ Request (application/json)

        {
            "merchant_id": 1,
            "name": "巨无霸",
            "image": "https://api.kuaidian.com/a.png",
            "type": "汉堡",
            "price": 100,
            "introduction": "由牛肉、青菜组成"
        }

+ Response 201 (application/json)

    + Headers

            Location: /foods/food_id

    + Body

            {
                "status": "OK",
                "message": "成功创建",
                "data": {
                    "food_id": 1,
                    "merchant_id": 1,
                    "name": "巨无霸",
                    "image": "https://api.kuaidian.com/a.png",
                    "type": "汉堡",
                    "price": 100,
                    "introduction": "由牛肉、青菜组成"
                }
            }

### Get a Food by FoodID [GET /foods/food_id]

+ Response 200 (application/json)

        {
            "status": "OK",
            "message": "成功获取",
            "data": {
                "food_id": 1,
                "merchant_id": 1,
                "name": "巨无霸",
                "image": "https://api.kuaidian.com/a.png",
                "type": "汉堡",
                "price": 100,
                "introduction": "由牛肉、青菜组成"
            }
        }

### Update a Food by FoodID [PATCH /foods/food_id]

+ Request (application/json)

        {
            name: "麦辣鸡翅"
        }

+ Response 200 (application/json)

        {
            "status": "OK",
            "message": "成功更新",
            "data": {
                "food_id": 1,
                "merchant_id": 1,
                "name": "麦辣鸡翅",
                "image": "https://api.kuaidian.com/a.png",
                "type": "汉堡",
                "price": 100,
                "introduction": "由牛肉、青菜组成"
            }
        }

### Delete a Food by FoodID [DELETE /foods/food_id]

+ Response 200 (application/json)

        {
            "status": "OK",
            "message": "成功删除"
        }


##Orders [/orders]

### Get all Orders by OpenID [GET /orders?open_id=?]

+ Response 200 (application/json)

        {
            "status": "OK",
            "message": "成功获取",
            "data": [
                {
                    "id": 23,
                    "merchant_id": 1,
                    "merchant_name": "兰州牛肉",
                    "merchant_tel": "12341234123",
                    "open_id": "abc",
                    "desk_id": 2,
                    "num_of_people": 3,
                    "paid": true,
                    "foods": ["汉堡, 12.5, 1", "芝士蛋糕, 22.5, 2"],
                    // "foods": "汉堡,12.5,1,芝士蛋糕,22.5,2",
                    "remark": "不要辣",
                    "create_at": "Thu Jun 28 2018 23:52:21 GMT+0800 (CST)"
                }, {
                    "id": 33,
                    "merchant_id": 1,
                    "merchant_name": "兰州牛肉",
                    "merchant_tel": "12341234123",
                    "open_id": "abc",
                    "desk_id": 2,
                    "num_of_people": 3,
                    "paid": true,
                    "foods": ["汉堡, 12.5, 1", "芝士蛋糕, 22.5, 2"],
                    "remark": "不要辣",
                    "create_at": "Thu Jun 28 2018 23:52:21 GMT+0800 (CST)"
                }
            ]
        }

### Create a New Order [POST]

+ Request (application/json)

        {
            "merchant_id": 1,
            "merchant_name": "兰州牛肉",
            "merchant_tel": "12341234123",
            "open_id": "abc",
            "desk_id": 2,
            "num_of_people": 3,
            "paid": true,
            "foods": ["汉堡, 12.5, 1", "芝士蛋糕, 22.5, 2"],
            "remark": "不要辣"
        }

+ Response 201 (application/json)

    + Headers

            Location: /orders/order_id

    + Body

            {
                "status": "OK",
                "message": "成功创建",
                "data": {
                    "id": 23,
                    "merchant_id": 1,
                    "merchant_name": "兰州牛肉",
                    "merchant_tel": "12341234123",
                    "open_id": "abc",
                    "desk_id": 2,
                    "num_of_people": 3,
                    "paid": true,
                    "foods": ["汉堡, 12.5, 1", "芝士蛋糕, 22.5, 2"],
                    "remark": "不要辣",
                    "create_at": "Thu Jun 28 2018 23:52:21 GMT+0800 (CST)"
                }
            }

### Get an Order by OrderID [GET /orders/order_id]

+ Response 200 (application/json)

        {
            "status": "OK",
            "message": "成功获取",
            "data": {
                "order_id": 23,
                "merchant_id": 1,
                "merchant_name": "兰州牛肉",
                "merchant_tel": "12341234123",
                "open_id": "abc",
                "desk_id": 2,
                "num_of_people": 3,
                "paid": true,
                "foods": ["汉堡, 12.5, 1", "芝士蛋糕, 22.5, 2"],
                "remark": "不要辣",
                "create_at": "Thu Jun 28 2018 23:52:21 GMT+0800 (CST)"
            }
        }

### Get orders by MerchantID [GET /orders/merchant_id]

+ Response 200 (aplication/json)

        {
            "status": "OK",
            "message": "成功获取",
            "data":[
                {
                    "id": 23,
                    "merchant_id": 1,
                    "merchant_name": "兰州牛肉",
                    "merchant_tel": "12341234123",
                    "open_id": "abc",
                    "desk_id": 2,
                    "num_of_people": 3,
                    "paid": true,
                    "foods": ["汉堡, 12.5, 1", "芝士蛋糕, 22.5, 2"],
                    "remark": "不要辣",
                    "create_at": "Thu Jun 28 2018 23:52:21 GMT+0800 (CST)"
                },
                {
                    "id": 33,
                    "merchant_id": 1,
                    "merchant_name": "兰州牛肉",
                    "merchant_tel": "12341234123",
                    "open_id": "abc",
                    "desk_id": 2,
                    "num_of_people": 3,
                    "paid": true,
                    "foods": ["汉堡, 12.5, 1", "芝士蛋糕, 22.5, 2"],
                    "remark": "不要辣",
                    "create_at": "Thu Jun 28 2018 23:52:21 GMT+0800 (CST)"
                }
            ]
        }

### Update an Order by OrderID [PATCH /orders/order_id]

+ Request (application/json)

        {
            "paid": true
        }

+ Response 200 (application/json)

        {
            "status": "OK",
            "message": "成功更新",
            "data": {
                "id": 23,
                "merchant_id": 1,
                "merchant_name": "兰州牛肉",
                "merchant_tel": "12341234123",
                "open_id": "abc",
                "desk_id": 2,
                "num_of_people": 3,
                "paid": true,
                "foods": ["汉堡, 12.5, 1", "芝士蛋糕, 22.5, 2"],
                "remark": "不要辣",
                "create_at": "Thu Jun 28 2018 23:52:21 GMT+0800 (CST)"
            }
        }

### Delete an Order by OrderID [DELETE /orders/order_id]

+ Response 200 (application/json)

        {
            "status": "OK",
            "message": "成功删除"
        }
        
