-- MySQL Script generated by MySQL Workbench
-- Mon Jun  4 01:08:12 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema clidb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clidb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clidb` DEFAULT CHARACTER SET utf8 ;
USE `clidb` ;

-- -----------------------------------------------------
-- Table `clidb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clidb`.`User` (
  `openId` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`openId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
